export const profile = {
  name: "Uday Deshmukh",
  title: "AI & ML Student | Cybersecurity & Ethical Hacking Enthusiast | Published Author",
  shortBio: "Building intelligent systems, exploring cybersecurity, and sharing knowledge through technology and writing.",
  email: "udaydeshmukh266@gmail.com",
  github: "https://github.com/Uday-deshmukh1",
  linkedin: "https://www.linkedin.com/in/uday-deshmukh-b8170a397?utm_source=share_via&utm_content=profile&utm_medium=member_android",
  instagram: "https://www.instagram.com/uday_deshmukh.i?igsh=MXg1OW1qamhzbDgwOQ==",
  college: "Major: CSE (AI & ML) | Minor: Electronics & Telecommunication Engineering (IoT)",
  location: "India",
};

export const stats = [
  { label: "Followers", value: 5000, suffix: "+" },
  { label: "Certifications", value: 18, suffix: "+" },
  { label: "Projects", value: 6, suffix: "+" },
  { label: "Hackathons", value: 3, suffix: "+" },
  { label: "Published Books", value: 3, suffix: "" },
];

export const skillCategories = [
  {
    name: "CYBERSECURITY",
    items: [
      "Ethical Hacking",
      "Penetration Testing",
      "Social Engineering",
      "Malware Analysis",
      "Kali Linux",
      "Kali Linux Commands",
      "Kali Linux Tools",
    ],
  },
  {
    name: "ARTIFICIAL INTELLIGENCE",
    items: [
      "Prompt Engineering",
      "AI Content Generation",
      "AI Ethics",
    ],
  },
  {
    name: "PROGRAMMING LANGUAGES",
    items: [
      "Java",
      "C Programming",
      "Python",
      "JavaScript",
    ],
  },
  {
    name: "WEB DEVELOPMENT",
    items: [
      "HTML",
      "CSS",
    ],
  },
  {
    name: "TOOLS AND PLATFORMS",
    items: [
      "GitHub",
      "Google Analytics",
    ],
  },
  {
    name: "SOFT SKILLS",
    items: [
      "Teamwork",
      "Problem Solving",
      "Project Management",
    ],
  },
  {
    name: "DOMAIN KNOWLEDGE",
    items: [
      "Data Privacy",
    ],
  },
];

export const certificates = [
  {
    rank: 1,
    title: "Prompt Engineering for AI",
    issuer: "AICTE + EduSkills (Ministry of Education, Government of India)",
    date: "Outstanding (90-100) · Mar 2026",
    tags: ["Government Backed", "AI Domain"],
    logo: "AI",
    color: "#FF9933",
    href: `${import.meta.env.BASE_URL}certificates/prompt-engineering-ai-eduskill.pdf`,
  },
  {
    rank: 2,
    title: "Ethical Hacking Internship",
    issuer: "AICTE + EduSkills (IIT Bombay SINE)",
    date: "8 weeks · Jun 2026",
    tags: ["Government Backed", "Cybersecurity"],
    logo: "EH",
    color: "#FF9933",
    href: `${import.meta.env.BASE_URL}certificates/ethical-hacking-uday-deshmukh.pdf`,
  },
  {
    rank: 3,
    title: "Java Training",
    issuer: "IIT Bombay (EduPyramids / SINE)",
    date: "Score 85% · 4 Credits · Jun 2026",
    tags: ["IIT Bombay", "Java", "4 Credits"],
    logo: "IIT",
    color: "#1E3A8A",
    href: `${import.meta.env.BASE_URL}certificates/uday-deshmukh-java-certificate.pdf`,
  },
  {
    rank: 4,
    title: "Cybersecurity Fundamentals",
    issuer: "IBM SkillsBuild",
    date: "Feb 2026 · Credly Verified",
    tags: ["IBM", "Credly Verified"],
    logo: "IBM",
    color: "#006699",
    href: `${import.meta.env.BASE_URL}certificates/ibm-cybersecurity-fundamentals.png`,
    image: `${import.meta.env.BASE_URL}certificates/ibm-cybersecurity-fundamentals.png`,
  },
  {
    rank: 5,
    title: "Ethical Hacker",
    issuer: "Cisco Networking Academy",
    date: "Feb 2026",
    tags: ["Cisco", "Ethical Hacker"],
    logo: "CEH",
    color: "#1BA0D7",
    href: `${import.meta.env.BASE_URL}certificates/cisco-ethical-hacker-certificate.pdf`,
  },
  {
    rank: 6,
    title: "Cybersecurity Analyst Job Simulation",
    issuer: "TATA / Forage",
    date: "Jun 2026 · Forage Verified",
    tags: ["TATA", "Job Simulation"],
    logo: "TC",
    color: "#0047AB",
    href: `${import.meta.env.BASE_URL}certificates/tata-cybersecurity-certificate.pdf`,
  },
  {
    rank: 7,
    title: "CaseX at E-Summit 26",
    issuer: "IIT BHU (Indian Institute of Technology Varanasi)",
    date: "Apr 2026 · National Level",
    tags: ["IIT BHU", "Case Competition"],
    logo: "IIT",
    color: "#00E5FF",
    href: `${import.meta.env.BASE_URL}certificates/iit-bhu-certificate.pdf`,
  },
  {
    rank: 8,
    title: "Google Analytics Certification",
    issuer: "Google",
    date: "Feb 2026 · Expires Feb 2027",
    tags: ["Google", "Analytics"],
    logo: "GA",
    color: "#4285F4",
    href: `${import.meta.env.BASE_URL}certificates/google-analytics-certification-uday-deshmukh.pdf`,
    image: `${import.meta.env.BASE_URL}certificates/google-analytics-badge.png`,
  },
  {
    rank: 9,
    title: "GitHub Actions — Automate Dev Tasks",
    issuer: "Microsoft Learn",
    date: "Feb 2026",
    tags: ["Microsoft", "GitHub Actions", "DevOps"],
    logo: "MS",
    color: "#7C3AED",
    href: `${import.meta.env.BASE_URL}certificates/microsoft-learn-achievements-uday-deshmukh.pdf`,
  },
  {
    rank: 10,
    title: "Rising India Hackathon 1.0",
    issuer: "NIT Nagpur",
    date: "Apr 2026 · National Level",
    tags: ["Hackathon", "NIT"],
    logo: "NIT",
    color: "#7C3AED",
    href: `${import.meta.env.BASE_URL}certificates/nit-hackathon-certificate.pdf`,
  },
  {
    rank: 11,
    title: "Getting Started with Cisco Packet Tracer",
    issuer: "Cisco Networking Academy",
    date: "Feb 2026",
    tags: ["Cisco", "Networking"],
    logo: "CPT",
    color: "#1BA0D7",
    href: `${import.meta.env.BASE_URL}certificates/cisco-packet-tracer-certificate.pdf`,
  },
  {
    rank: 12,
    title: "Introduction to C++",
    issuer: "LearnTube",
    date: "Dec 2025",
    tags: ["C++"],
    logo: "C++",
    color: "#00E5FF",
    href: `${import.meta.env.BASE_URL}certificates/introduction-to-cpp-certificate.jpg`,
    image: `${import.meta.env.BASE_URL}certificates/introduction-to-cpp-certificate.jpg`,
  },
  {
    rank: 13,
    title: "C Programming Course for Beginners",
    issuer: "LearnTube",
    date: "Dec 2025",
    tags: ["C Programming"],
    logo: "C",
    color: "#7C3AED",
    href: `${import.meta.env.BASE_URL}certificates/c-programming-uday-deshmukh.pdf`,
  },
];

export const books = [
  {
    title: "Karna: A Life of Sacrifice",
    author: "Uday Deshmukh",
    summary:
      "A retelling of the life of Karna, one of the greatest warriors of Indian mythology, exploring his journey from childhood to adulthood through themes of courage, loyalty, and sacrifice.",
    url: "https://play.google.com/store/books/details?id=ZzSrEQAAQBAJ",
    coverColor: "from-amber-600 to-red-800",
    icon: "⚔",
  },
  {
    title: "Some Feelings Are Never Said",
    author: "Uday Deshmukh",
    summary:
      "A heartfelt collection of emotions and unspoken feelings, exploring the quiet moments of love, longing, and the sentiments that often go unexpressed.",
    url: "https://play.google.com/store/books/details?id=wJ25EQAAQBAJ",
    coverColor: "from-purple-600 to-pink-700",
    icon: "💭",
  },
];
